### ISSUE TITLE
interop: all-uppercase attribute names

### ISSUE THREAD

**Issue by chochos** [ceylon/ceylon-lang.org#138]
I don't know if this is a special case or if it applies to any all-uppercase attribute name, but I had a hard time figuring out how to set a `URL` property on an object. Turns out it's `object.url:=value`. So it might be worth mentioning this conversion in the interop section, right after the `\i` and `\I` bits.

**Comment by quintesse** [comment]
Is this issue still relevant?

**Comment by chochos** [comment]
well has it been documented?

**Comment by quintesse** [comment]
Don't ask me, you're the one that opened this issue ;)

**Comment by tombentley** [comment]
Is this still really necessary now that the typechecker offers "did you mean xxx?" proposals? I mean we could document the precise algorithm we use, and note how it may differ slightly from the java beans spec, but I can't see anyone getting confused enough while in the IDE to think "Oh, I wonder if this is documented on the website somewhere..."

So I'm going to close this. Reopen if you really want it.

**Comment by gavinking** [comment]
It is already documented in the tour.
