### ISSUE TITLE
Some more examples about the use of Type Parameters would be nice

### ISSUE THREAD

**Issue by lukaseder** [ceylon/ceylon-lang.org#185]
This documentation page is pretty brief about how to use "generics" / type parameters in Ceylon:
http://ceylon-lang.org/documentation/1.0/reference/structure/type-parameters/

It would be nice to see some more useful examples for a couple of use-cases. From the language specs, I understand that the generics support in Ceylon is much more sophisticated than in Java:
http://ceylon-lang.org/documentation/1.0/spec/html/typesystem.html#generictypeparameters

... specifically given the generic type constraints features:
http://ceylon-lang.org/documentation/1.0/spec/html/typesystem.html#generictypeconstraints

So, not only would it be helpful to have some examples in the reference pages, it would also be a good marketing thing, to show that Ceylon builds upon a very sophisticated type system

**Comment by quintesse** [comment]
Is this issue still relevant?

**Comment by tombentley** [comment]
I've added a link to the tour discussion of generics.
