### ISSUE TITLE
Interop section about Java collections

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-lang.org#212]
http://m.infoworld.com/d/application-development/first-look-gavin-kings-ceylon-217197?page=0,1 shows that we need more documentation about this.

**Comment by quintesse** [comment]
Is this issue still relevant?

**Comment by tombentley** [comment]
Closing this as it's not clear exactly what documentation is really needed. 

* The types are different
* There's less friction now anyway, as things like `for` can iterate Java iterables
* If there's a problem with compiler error messages not spelling out that your java.util.ArrayList is not assignable to your ceylon.language.List, that would be an issue for the typechecker, not the website.

**Comment by gavinking** [comment]
I have already documented it in the tour anyway.
