### ISSUE TITLE
Include build instructions on the "Get the Source" page

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-lang.org#238]
On the "Get the source" page (http://ceylon-lang.org/code/source/) we list all the repos, but do not explain how to build anything. While that *is* explained on the "Contribute" page (http://ceylon-lang.org/code/contribute/), it's not the most obvious place to look if you're not yet interested in contributing. 

We need at least a link to the build instructions at the bottom of the "Get the source" page. But we should also consider:

* include the build instructions on the "Get the source" page
* split it out of both and have some kind of "Building Ceylon" page

**Comment by quintesse** [comment]
There's a link now on that page I see. And we haven't had any complaints in 3 years. So I'm closing this.
