### ISSUE TITLE
Describe the resources mechanism

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-lang.org#243]
In ceylon/ceylon-compiler#881 we added the handling of resources to the compiler, we need to document how this works.

**Comment by FroMage** [comment]
AFAICT this is not done yet and it's severely lacking. Has to be done ASAP. If it's done, it's not anywhere obvious and we have to improve its discoverability.

**Comment by quintesse** [comment]
Btw I think we should improve the whole bit about directory structure, `source`, `resource`, `script`, `modules`. If it's described somewhere it's not easy to find either.

**Comment by tombentley** [comment]
Awooga awooga @quintesse: Oct 2013!

**Comment by quintesse** [comment]
I promise I'll do it first thing after the release ;)

**Comment by FroMage** [comment]
I've a feeling I've heard this before…

**Comment by quintesse** [comment]
Nah, that's just old age twisting your neurons

**Comment by quintesse** [comment]
Hope this is good enough: http://www.ceylon-lang.org/documentation/1.2/reference/tool/project/

**Comment by FroMage** [comment]
That's pretty good, but it would be better with either a code example on how to use those resources, or a pointer to where that is documented.

**Comment by quintesse** [comment]
It has that, it points to the docs of `Resource` which has an example.

**Comment by quintesse** [comment]
I had thought about a separate page about resources, but I couldn't think of any better example than the one already provided with the docs of `Resource` so it seemed a bit superfluous.

**Comment by FroMage** [comment]
OK right, I missed it. Fine then, great!
