### ISSUE TITLE
Known Issues page needs a rethink

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-lang.org#250]
This page just gets nastily out of date. We need to rethink how we handle this one. I think it would be much better if we had a git issue tracker tag that we could apply to issues if we want them to appear on that page.

**Comment by quintesse** [comment]
Is this issue still relevant?

**Comment by lucaswerkmeister** [comment]
Well, we still have the [page](http://ceylon-lang.org/documentation/1.2/faq/known-issues/), and it’s still bad, so I’d say yes…

**Comment by quintesse** [comment]
Ok, I didn't even know where to look for it. In the FAQ, okay.

Shouldn't we simply remove it? I don't see the added value of this page.

**Comment by tombentley** [comment]
I agree with @quintesse that these pages aren't especially useful, so I'm going to remove them. If @FroMage or someone wants them that's fine, but they should ensure we don't have to update them by hand. We could use a tag on issues in github, for example.
