### ISSUE TITLE
make Red Hat more prominent on home page

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-lang.org#282]
I never noticed before, but from our website it's almost impossible to see the association with Red Hat.

Unless you look at [this buried page](http://ceylon-lang.org/community/companies/) or at the copyright notice in the footer, you would not even notice.

Clearly we need to do more to play up the support of Red Hat, since that is something that matters to a lot of potential users.

**Comment by FroMage** [comment]
Bumping because I read comments that people did not know RH was behind this and that sucks.

**Comment by gavinking** [comment]
Totally this is idiotic that we have gone for how many years meaning to do this and never having done it!

**Comment by gavinking** [comment]
@insectengine is this something you could help us with, DYT?

**Comment by FroMage** [comment]
I am going to fix this today or never.

See https://www.openshift.org or https://getfedora.org for inspiration. Both put the Red Hat logo at the bottom.

I'll do just this. OK?

**Comment by gavinking** [comment]
Fine but use the one from the openshift site 'cos it is in HD. The fedora one is blurry.

**Comment by FroMage** [comment]
OK that's ridiculous, I need to get myself a HiDPI (NOT HD Gavin!!!) display I don't even see those issues.

**Comment by lucaswerkmeister** [comment]
“HD”, in this case, means “SVG” – infinitely scalable :)

**Comment by FroMage** [comment]
Seriously?

**Comment by gavinking** [comment]
I was in fact trying to say "high density".

**Comment by FroMage** [comment]
Wow cool. I never dared to do that myself. I guess we can now? That will save me doing it manually.

**Comment by FroMage** [comment]
HiDPI is the acronym for "high density"

**Comment by FroMage** [comment]
I agree it's fucked up they wasted HD on high definition but what can you do…

**Comment by FroMage** [comment]
Done. WDYT?

**Comment by gavinking** [comment]
It's fine. I was actually trying to think of some way to make it even _more_ prominent, instead of just putting it in the footer. But that's good for now.

**Comment by lucaswerkmeister** [comment]
LGTM, but how come

> Site generated October 30, 2015 at 11:29

when you just now pushed the patch?

**Comment by FroMage** [comment]
That machine is in the US.

**Comment by FroMage** [comment]
> It's fine. I was actually trying to think of some way to make it even more prominent, instead of just putting it in the footer. But that's good for now.

We could be holier than fedora and openshift, but that's what they've done and they are very similar project-wise to what we do with Ceylon wrt Red Hat, no?

**Comment by FroMage** [comment]
I mean, it appears to be a company-wide theme.

**Comment by gavinking** [comment]
OK, fine. It's not as if I have a clear proposal.

I just feel stupid that it took us three years to do this trivial thing.

**Comment by FroMage** [comment]
Yes, well, now it's done. Never too late to fix past mistakes ;)
