### ISSUE TITLE
Document configuration file options for ceylondoc

### ISSUE THREAD

**Issue by thradec** [ceylon/ceylon-lang.org#288]
- `header` The header text to be placed at the top of each page.
- `footer` The footer text to be placed at the bottom of each page.
- `non-shared`  Includes documentation for package-private declarations.
- `source-code` Includes source code in the generated documentation.
- `ignore-broken-link` Do not print warnings about broken links.
- `ignore-missing-doc` Do not print warnings about missing documentation.
- `ignore-missing-throws` Do not print warnings about missing throws annotation.
- `link` The URL or path of a module repository containing documentation for
          external dependencies.

**Comment by quintesse** [comment]
Is this issue still relevant?

**Comment by tombentley** [comment]
Yes, I think it is. I think they should really be part of the tool
documentation though, not a separate bit of documentation on the website.

**Comment by quintesse** [comment]
So then it isn't relevant here but should be moved to the ceylon repo as an issue for the doc tool?

**Comment by tombentley** [comment]
I guess so, but we really need a way to systematically know which configuration options each tool respects, because otherwise it's a pain to keep up to date.

**Comment by tombentley** [comment]
Closing because we now have ceylon/ceylon#6691
