### ISSUE TITLE
Link from tour/interop to reference/interop

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-lang.org#337]
Because there's a lot more info in the reference and that's not clear at all from the tour.

**Comment by tombentley** [comment]
In general the tour is quite self-contained and doesn't really link out to much. I guess it's up to @gavinking if he wants to change that.

**Comment by quintesse** [comment]
Is this issue still relevant?

**Comment by tombentley** [comment]
I think if @gavinking wanted the tour to link to the reference he would have done so by now. If he disagrees he can reopen this.
