### ISSUE TITLE
link from blogpost

### ISSUE THREAD

**Issue by Eternity-Yarr** [ceylon/ceylon-lang.org#340]
http://ceylon-lang.org/blog/2015/06/12/more-type-functions/ have link to http://ceylon-lang.org/blog/2015/06/12/more-type-functions/2015/06/03/generic-function-refs which is 404

**Comment by Eternity-Yarr** [comment]
Appears like one forgot make it absolute

**Comment by gavinking** [comment]
Thanks, fixed!
