### ISSUE TITLE
Reference about unary plus operator and negation operator are outdated

### ISSUE THREAD

**Issue by Zambonifofex** [ceylon/ceylon-lang.org#341]
The reference about the unary plus operator and the negation operator are outdated, mentioning the now nonexistent members `positiveValue` and `negativeValue` of the interface `Invetible`.
http://ceylon-lang.org/documentation/current/reference/operator/unary_plus/
http://ceylon-lang.org/documentation/current/reference/operator/unary_minus/
http://ceylon-lang.org/documentation/current/reference/operator/operator-polymorphism/

**Comment by lucaswerkmeister** [comment]
See ceylon/ceylon.language#229.

**Comment by gavinking** [comment]
Well, we're still yet to update the documentation for Ceylon 1.2.

**Comment by gavinking** [comment]
Oh wait, that change was in 1.1?

**Comment by lucaswerkmeister** [comment]
Yup:
https://github.com/ceylon/ceylon.language/blob/1.1.0/src/ceylon/language/Invertible.ceylon

**Comment by gavinking** [comment]
OK, fixed, thanks.

**Comment by lucaswerkmeister** [comment]
Is unary + still polymorphic? (I guess it kinda depends on the
“Invertible” interface in that it’s only defined for Invertible instances.)

Oh, and unrelated, but I just noticed that the + doc says - instead of +
under Type – copy+paste error :)
