### ISSUE TITLE
Page Not Found in Link to Vert.x documentation 

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-lang.org#343]
Open the page: http://ceylon-lang.org/documentation/current/ and try to click it

**Comment by lucaswerkmeister** [comment]
I think this might be because of the Vert.x 3 release – which doesn’t have a Ceylon version yet. The Ceylon documentation for Vert.x 2 is now at http://vertx.io/vertx2/core_manual_ceylon.html.

**Comment by tombentley** [comment]
The link seems to be fine today, so I guess when vertex 3 got release it started working again.
