### ISSUE TITLE
document semantics of native

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-lang.org#346]
We need a page in the documentation section that documents `native`.

**Comment by tombentley** [comment]
We still need to document `native` on the website.

**Comment by tombentley** [comment]
ping @quintesse 

I'd personally find this useful.

**Comment by quintesse** [comment]
I've got quite a bit written already, need to finish it still.

**Comment by quintesse** [comment]
Finally merged to native docs. Closing.
