### ISSUE TITLE
Ceylon guidelines on using union return values vs exceptions

### ISSUE THREAD

**Issue by xkr47** [ceylon/ceylon-lang.org#360]
At https://gitter.im/ceylon/user?at=56447f82b55b6d3150941d6c (and the following comments by @gavinking) there was the culmination of a longer discussion about union return values vs exceptions. I thought it would be nice to talk a little about that in (for example) the Tour.

**Comment by gavinking** [comment]
@xkr47 I have blogged on this topic and added links from the tour and language design FAQ.

Do you think that is enough? Do you have additional suggestions?

**Comment by xkr47** [comment]
Very nice article. Posted some comments there. Thanks!
