### ISSUE TITLE
Horribly outdated reference for satisfies operator

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-lang.org#373]
http://ceylon-lang.org/documentation/1.2/reference/operator/satisfies/

```ceylon
void m(Type<Anything> x) {
    Boolean satisfaction = satisfies String Iterator;
}
```
> Incorrect syntax: no viable alternative at token satisfies
> Incorrect syntax: no viable alternative at token Iterator

There is no such thing as a “satisfies operator”. I’m not sure if it’s seriously planned at this point (certainly not with this syntax, I would think – that looks like a prefix condition, not like a postfix expression), but it definitely shouldn’t be on the reference, where it’s just going to confuse users.

The page weakly indicates that this is not a current feature, but that’s also outdated:
> **Ceylon 1.1 or later**
> Support for this feature will be introduced in Ceylon 1.1 or later

I guess with the “or later”, it’s technically not *wrong* :D

**Comment by gavinking** [comment]
I fixed the tag. In fact these pages aren't linked to from anywhere, AFICS.
