### ISSUE TITLE
else and then operator pages have misleading descriptions

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-lang.org#380]
It looks like the pages for `else` and `then` conflate the operators with `if` expressions. Or am I missing something?

http://ceylon-lang.org/documentation/1.2/reference/operator/then/
http://ceylon-lang.org/documentation/1.2/reference/operator/else/

**Comment by tombentley** [comment]
I agree that the descriptions are not helpful. We should probably be very explicit about the differences between the `then`/`else` construct and `if`/`then`/`else` expressions, because it is likely going to confuse people first time they notice there's both.

**Comment by quintesse** [comment]
@tombentley Is this issue still relevant? I see you referenced this from a commit.

**Comment by tombentley** [comment]
I think this is fixed. @jvasileff can always reopen if he disagrees.
