### ISSUE TITLE
Links to page source on github

### ISSUE THREAD

**Issue by xkr47** [ceylon/ceylon-lang.org#381]
Would you consider adding "View source" links to all documentation pages? Example:

![ceylon-doc-view-source2](https://cloud.githubusercontent.com/assets/1488474/11713487/6e41f63c-9f3c-11e5-9c78-9bf32e4fb635.png)

would link to https://github.com/ceylon/ceylon-lang.org/blob/master/documentation/1.2/reference/interoperability/js/native-anno.md. Users could then fork/edit the file on github and create pull requests with little effort.

You could optionally show a popup with links to guidelines and other information you would like users to know before editing pages.

**Comment by lucaswerkmeister** [comment]
> You could optionally show a popup with links to guidelines and other information you would like users to know before editing pages.

https://github.com/blog/1184-contributing-guidelines

**Comment by tombentley** [comment]
Looks like this was implemented a while ago. See for example https://ceylon-lang.org/documentation/1.3/reference/annotation/final/

**Comment by xkr47** [comment]
This is great, thanks!
