### ISSUE TITLE
Ceylon SDK doc links should point to module-doc/api/index.html, not to the module-doc directory

### ISSUE THREAD

**Issue by ePaul** [ceylon/ceylon-lang.org#383]
Looking at the ["API docs for `ceylon.language` and the Ceylon SDK"](http://ceylon-lang.org/documentation/1.2/reference/#api_docs_for_ceylon_language_and_the_ceylon_sdk) section in the reference, the links there all link to URIs like https://herd.ceylon-lang.org/repo/1/ceylon/math/1.2.0/module-doc. From there, we need two more clicks to get to the actual page like https://modules.ceylon-lang.org/repo/1/ceylon/math/1.2.0/module-doc/api/index.html, and for larger packages I even have to search the index.html in a larger list first.

The links should go directly to that index.html page.

**Comment by gavinking** [comment]
Thanks, fixed.
