### ISSUE TITLE
HTTPS connection to ceylon-lang.org gives 403 Forbidden

### ISSUE THREAD

**Issue by lukehutch** [ceylon/ceylon-lang.org#389]
Trying to connect to [https://ceylon-lang.org/](https://ceylon-lang.org/) gives:

```
403 Forbidden
You don't have permission to access / on this server.
Apache/2.2.15 (Red Hat) Server at ceylon-lang.org Port 443
```

**Comment by sadmac7000** [comment]
Using regular http should fix this. Apparently it's a change due to the web IDE not working right on https. I'd hope we could at least redirect...

**Comment by lucaswerkmeister** [comment]
It’s not a change, we never supported HTTPS. See #255, #257, #335, #354. Though now that we have a valid certificate, we could indeed at least redirect to the HTTP version, until #354 is done.

**Comment by bjansen** [comment]
The website is now HTTPS-only, closing.
