### ISSUE TITLE
ceylon-lang.org has a 404

### ISSUE THREAD

**Issue by mario-campos** [ceylon/ceylon-lang.org#393]
When browsing to http://ceylon-lang.org/documentation/1.2/reference/structure/module/overrides, I get...

> Oh no!
> We can't seem to find that page.

**Comment by lucaswerkmeister** [comment]
Where did you find a link to that document? I think it’s located at http://ceylon-lang.org/documentation/1.2/reference/repository/overrides/ (if I’m guessing it correctly from your URL), so perhaps we need to update an old link.

**Comment by mario-campos** [comment]
If you go to the Ceylon documentation on [`module`](http://ceylon-lang.org/documentation/1.2/reference/structure/module/), and scroll down to *See Also*, you'll find "You can [override dependences](http://ceylon-lang.org/documentation/1.2/reference/structure/module/overrides) for Maven and Ceylon modules"
