### ISSUE TITLE
Weird redirect

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-lang.org#397]
If I go to https://www.ceylon-lang.org/download/dist/1_2_2 I get a 404, but if I then change it to http://www.ceylon-lang.org/download/dist/1_2_2 it starts the download.... by redirecting to the first version!

How is that possible?

Anyway, I need the first version to work for the Bootstrap downloads :)

**Comment by lucaswerkmeister** [comment]
It doesn’t redirect to the first version – it redirects to https://downloads.ceylon-lang.org/cli/ceylon-1.2.2.zip (both in the Location header and in the served 302 document), which is a proper zip file link and also works as a standalone link.

Although, with #354 – which, as far as I’m aware, is no longer blocked by anything! – it *should* redirect to the exact same URL with HTTPS protocol, which then should work…

**Comment by quintesse** [comment]
You're right, I must be blind
