### ISSUE TITLE
Roadmap page is boring!

### ISSUE THREAD

**Issue by ncorai** [ceylon/ceylon-lang.org#404]
Why can't it track patch releases too?

**Comment by Zambonifofex** [comment]
*ahem* 404 issue not found.

Sorry. :-P

**Comment by Zambonifofex** [comment]
Also, given the very vague description, for a second I tough you were the troll.

I blame you, for not having an avatar!

**Comment by ncorai** [comment]
Agreed about the avatar, it's now done.

For the roadmap page, I'm serious. It's been empty for almost 5 months and I don't see work starting in earnest on 1.3 for a little while longer. I gives the impression that no future work is planned although nothing could be further from the truth.

Actually, I think it would be even better to simultaneously track progress on 1.2.3 and 1.3 on at least the Ceylon, Ceylon SDK, Eclipse and IntelliJ IDE projects.

Otherwise, go back to text descriptions: Android support is coming! Full Java 8 support! IntelliJ IDE! Exciting stuff...

**Comment by gavinking** [comment]
I just wrote up some stuff. A mini-roadmap. Does that help?

**Comment by ncorai** [comment]
Much better
