### ISSUE TITLE
Walkthrough doesn't mention hexadecimal literals.

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon-lang.org#411]
I had to go to the spec to recall how to do them. If it's on the site then there could be a discoverability issue. Perhaps these aren't needed often (given that I had to look them up) but it doesn't take much to mention them, and they do break from the convention of other languages.

May as well mention binary literals while we're at it.

**Comment by lucaswerkmeister** [comment]
They are documented in the [reference](http://ceylon-lang.org/documentation/1.2/reference/literal/integer/), for what it’s worth.
