### ISSUE TITLE
Mention `native` in the tour

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-lang.org#425]
As requested here: https://github.com/ceylon/ceylon/issues/4561

**Comment by ncorai** [comment]
Usage of the `native` annotation is now explained in `/tour/interop` and `/tour/dynamic`. Can this be closed?

**Comment by gavinking** [comment]
Yeah. I'm still not totally satisfied with the documentation for native, but it is at least "mentioned" now.
