### ISSUE TITLE
ceylon command comments

### ISSUE THREAD

**Issue by Kopilov** [ceylon/ceylon-lang.org#429]
Hello!
Note that all links on https://ceylon-lang.org/documentation/1.2/reference/tool/ceylon/ web page are broken.
We can use `ceylon help` in command line, but it will better to have online documentation also.

**Comment by FroMage** [comment]
OK, let me fix them.

**Comment by FroMage** [comment]
Fixed. @quintesse I had to move them:

```
mv 1.2/reference/tool/ceylon/subcommands/toolset/* 1.2/reference/tool/ceylon/subcommands/
```

Any idea how this came to be? Probably something wrong in the release process?

**Comment by FroMage** [comment]
Leaving open until we fix the release process so it doesn't happen again.

**Comment by tombentley** [comment]
I'm going to close this because certainly the 1.3 links are not broken.
