### ISSUE TITLE
Document new module import format

### ISSUE THREAD

**Issue by ncorai** [ceylon/ceylon-lang.org#430]
Currently, the namespace prefix isn't documented in the `reference/repository/maven` or in the `reference/structure/module` page. The `reference/repository/overrides` page should also be updated.

Arguably it should also be explained in the `/tour/modules` or at least in `tour/interop`. Maybe `reference/repository/maven` shouldn't be linked to as a _legacy_ page but more of an interop one, and other interop `reference/repository` pages should be created.

Most likely, there are other pages which should be updated too.

**Comment by gavinking** [comment]
@quintesse?

**Comment by ncorai** [comment]
This is now done.
