### ISSUE TITLE
Document is condition idiom when dealing with type erasure

### ISSUE THREAD

**Issue by ncorai** [ceylon/ceylon-lang.org#431]
As discussed in https://github.com/ceylon/ceylon/issues/6528, Java generics will force the use of workarounds such as
```ceylon
if (is JavaType<out Anything> value) {
    assert (is JavaType<ParamType> value);
    ...
}
```
The inconsistency between the behaviors of `if is` (error) and `assert is` (warning) and the resulting necessary idiom should be documented in `tour/interop/`, `reference/interoperability/java-from-ceylon/` and maybe `reference/operator/is/` and `reference/statement/conditions/#is_conditions`

**Comment by gavinking** [comment]
Yes, I agree, we need to explain this.

**Comment by gavinking** [comment]
Done.
