### ISSUE TITLE
TRY ONLINE buttons are all broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-lang.org#435]
The problem seems to be that I get a security error hitting:

<https://try.ceylon-lang.org/>

over HTTPS.

> Your connection is not private

> Attackers might be trying to steal your information from try.ceylon-lang.org (for example, passwords, messages, or credit cards). NET::ERR_CERT_AUTHORITY_INVALID

**Comment by bjansen** [comment]
Same here

**Comment by lucaswerkmeister** [comment]
[Qualys SSL Test](https://www.ssllabs.com/ssltest/analyze.html?d=try.ceylon%2dlang.org&latest) says we’re sending an incomplete chain (“DigiCert SHA2 High Assurance Server CA” missing), which is probably why it still works in Firefox (Firefox probably has the intermediate certificate in its trust store; all other browser use the OS’ trust store).

**Comment by quintesse** [comment]
It does work for me btw in Chrome on Windows and both Chrome and Firefox on Fedora.

**Comment by FroMage** [comment]
We've fixed this.
