### ISSUE TITLE
Add '/reference/annotation/static' page and update Tour of Ceylon

### ISSUE THREAD

**Issue by ncorai** [ceylon/ceylon-lang.org#437]
Currently, `/tour/classes` [denies](https://ceylon-lang.org/documentation/1.3/tour/classes#living_without_static_members) the existence of static members.

I'd also suggest updating `/tour/inheritance` to clarify the status of static members.

**Comment by gavinking** [comment]
Yes, I know, documenting `static` in the tour and in the _spec_ is already on my todo list for the next two days. I have to blog about it too.

**Comment by ncorai** [comment]
The issue was just to keep track of it, the amount of work you've put into the Tour of Ceylon is certainly appreciated.

**Comment by ncorai** [comment]
This has been done.
