### ISSUE TITLE
document destructuring in reference

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-lang.org#446]
The reference docs for:

- [`let`](https://ceylon-lang.org/documentation/1.3/reference/expression/let/)
- [`if` ](https://ceylon-lang.org/documentation/1.3/reference/statement/if/),
- [`switch`](https://ceylon-lang.org/documentation/1.3/reference/statement/switch/), and
- [`for`](https://ceylon-lang.org/documentation/1.3/reference/statement/for/).

should show examples using [destructuring](https://ceylon-lang.org/documentation/1.3/tour/sequences/#destructuring) in these constructs.

**Comment by tombentley** [comment]
@gavinking `for` and `let` already had examples. But let me know if you had better examples in mind. Also I suppose I should mention destructuring in `while` too.

**Comment by gavinking** [comment]
Well, since both `while` and `assert` support destructuring, I guess it would be better to cover this [here](https://ceylon-lang.org/documentation/1.3/reference/statement/conditions/).

**Comment by gavinking** [comment]
Great, thanks Tom!
