### ISSUE TITLE
Unintroduced terms

### ISSUE THREAD

**Issue by loldrup** [ceylon/ceylon-lang.org#456]
This lump of text from the [Ceylon tour](https://ceylon-lang.org/documentation/1.3/tour/initialization/#constructor_delegation) uses a bunch of terms which hasn't been introduced previously. It's like the text arrived in a time machine!

"If the class directly extends Basic, and the constructor does not explicitly delegate to another constructor, it is understood to implicitly delegate to initializer of Basic.

Constructors of a class which does not directly extend Basic must explicitly delegate.

Since constructors are restricted to delegate backwards, the general flow of member initialization in Ceylon is preserved: initialization flows forward from the beginning of the body of the class, and each member must be initialized before it is used. The gory details are covered here."

These are the unintroduced terms that are used:
 - Basic
 - initializer (constructor?)
 - member (class instances?)

**Comment by loldrup** [comment]
https://modules.ceylon-lang.org/repo/1/ceylon/language/1.1.0/module-doc/api/Basic.ceylon.html

**Comment by loldrup** [comment]
I could venture a guess:
Initializer == initializer section == whatever lump of imperative code happens to be in the top of the Class declaration

**Comment by loldrup** [comment]
is there a distinction between an initializer and an 'initializer section'?

the former being a short form for declaring classes without using a constructor, and, the latter being a sequence of code that can lurk at the top of a constructor?

**Comment by gavinking** [comment]
> This lump of text from the Ceylon tour uses a bunch of terms which hasn't been introduced previously. It's like the text arrived in a time machine!

That's just not true. _All_ these terms have been introduces in previous chapters!

**Comment by gavinking** [comment]
> is there a distinction between an initializer and an 'initializer section'?

Nope.

**Comment by gavinking** [comment]
Alright, so I have added some language at the start of chapter two to make very explicit what "member" means in that and following chapters. I've also clarified that "initializer" means "initializer section", and added a link to the discussion of `Basic` in the previous chapter.

I hope that addresses the concerns.

**Comment by loldrup** [comment]
same mistake - jumping to chapter 15 :)
