### ISSUE TITLE
Unclear code explanation

### ISSUE THREAD

**Issue by loldrup** [ceylon/ceylon-lang.org#457]
This piece of code from the [Ceylon tour](https://ceylon-lang.org/documentation/1.3/tour/initialization/#constructors_and_extension):

```
class Person(String name) {}

class Employee 
        extends Person { //just the class name
    shared new withName(String name) 
            extends Person(name) {} //instantiation
}
```

exemplifies a new concept (a class that extends another class).

Such a new concept should have its own dedicated sentence that gives a basic introduction to the concept, without involving any other contexts. That sentence should occur somewhere before the lump of code that exemplifies it.

A reader could perhaps be expected to understand what class extension means. If that is expected, then the explanatory sentence need not start from 'point blank'. It could simply be "in Ceylon, classes can extend other classes. In this example the class Employee is made to extend the class Person:"

(after that introduction the text could then go on to describe what line 6 and 7 in the code block is doing, and other relevant stuff)

What I'm basically trying to say is that this text:

> "When a class with a constructor extends a class with an initializer or default constructor, it specifies just the name of the extended class in the extends clause, and a regular instantiation in the extends clause of the constructor"

isn't a good preamble to the above code block.

**Comment by gavinking** [comment]
I don't understand. Class extension is explained in chapter 4 of the tour, and this is chapter _15_. By this point the reader should have a pretty strong grasp of the notion...

**Comment by gavinking** [comment]
I have added a link back to chapter 4. I hope that clarifies things.

**Comment by loldrup** [comment]
same mistake - jumping to chapter 15 :)
