### ISSUE TITLE
instantiation or constructor invocation?

### ISSUE THREAD

**Issue by loldrup** [ceylon/ceylon-lang.org#458]
In this lump of code:

```
class Person(String name) {}

class Employee 
        extends Person { //just the class name
    shared new withName(String name) 
            extends Person(name) {} //instantiation     (line 6)
}
```

line 6 is (seemingly) denoted an 'instantiation' by the accompanying text:

> "When a class with a constructor extends a class with an initializer or default constructor, it specifies just the name of the extended class in the extends clause, and a regular instantiation in the extends clause of the constructor:"

But, in this lump of code:

```
class Person {
    String name;
    shared new withName(String name) {
        this.name = name;
    }
}

class Employee 
        extends Person { //just the class name
    shared new withName(String name) 
            extends Person.withName(name) {} //constructor invocation    (line 11)
}
```

line 11 is (seemingly) denoted a 'constructor invocation' by the accompanying text:

> "When a class with a constructor extends a class with a named constructor, it specifies just the name of the extended class in the extends clause, and a regular constructor invocation in the extends clause of the constructor"

Are these two denotations consistent with each other, and the code? It seems to me they denote the exact same thing, thus is send weird that two different terms are used to describe them.

[Source](https://ceylon-lang.org/documentation/1.3/tour/initialization/#constructors).

**Comment by gavinking** [comment]
Well, yes. A "regular instantiation" and a "regular constructor invocation" are just two different kinds of instantiation expression. So, indeed, the two code snippets are exhibiting very similar things.

I don't see anything wrong here.

**Comment by loldrup** [comment]
My mistake was to follow a link and then all of a sudden be in chapter 15, which is a bit hard to understand straight from chapter 4 :)

**Comment by gavinking** [comment]
@loldrup OK :)
