### ISSUE TITLE
Misplaced buttons

### ISSUE THREAD

**Issue by cloudvapour** [ceylon/ceylon-lang.org#480]
The "View Source" and "Edit" buttons in the [Tour of Ceylon](https://ceylon-lang.org/documentation/1.3/tour/) are misplaced, part of the words are overlapped with the image.

![image](https://user-images.githubusercontent.com/30367398/28955177-2347aada-7917-11e7-886d-48553195e236.png)

**Comment by FroMage** [comment]
Weird, they render fine for me.

**Comment by FroMage** [comment]
Pushed a change. Is it better for you?

**Comment by cloudvapour** [comment]
Yes thanks

**Comment by FroMage** [comment]
Great, thanks.
