### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by loldrup** [ceylon/ceylon-lang.org#482]
this address gives 'not found':
https://herd.ceylon-lang.org/repo/1/ceylon/http/server/1.3.2/module-doc/api/StartsWith.type.html

the link was found here:
https://herd.ceylon-lang.org/modules/ceylon.http.server/1.3.2/members

**Comment by loldrup** [comment]
actually, ALL the links (in the list) are broken

**Comment by loldrup** [comment]
actually, SEVERAL of the links (in the list) are broken

**Comment by loldrup** [comment]
incl. this one:
https://herd.ceylon-lang.org/repo/1/ceylon/http/server/1.3.2/module-doc/api/index.html%23newServer

**Comment by FroMage** [comment]
Thanks, that's a Herd issue, I've moved it: ceylon/ceylon-herd#289
Thanks for reporting!
